# Generated by Django 5.2.7 on 2025-10-10 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('to-do', 'Todo'), ('`in-progress', 'Inprogress'), ('review', 'Review'), ('done', 'Done')])),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')])),
                ('due_date', models.DateField()),
                ('comments_count', models.IntegerField(default=0)),
                ('assignee', models.ManyToManyField(related_name='task_assignee', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ManyToManyField(related_name='task_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
