# Generated by Django 5.2.7 on 2025-10-10 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
