# Generated by Django 5.2.7 on 2025-10-10 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_delete_tasks'),
        ('tasks', '0002_remove_tasks_assignee_remove_tasks_reviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.boards'),
            preserve_default=False,
        ),
    ]
