# Generated by Django 5.2.7 on 2025-10-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='comments_count',
        ),
    ]
