# Generated by Django 5.2.7 on 2025-10-08 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('member_count', models.IntegerField()),
                ('ticket_count', models.IntegerField()),
                ('tasks_to_do_count', models.IntegerField()),
                ('tasks_high_prio_count', models.IntegerField()),
                ('members', models.ManyToManyField(related_name='boards_members', to=settings.AUTH_USER_MODEL)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
