# Generated by Django 5.2.7 on 2025-10-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_board_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='tasks_high_prio_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boards',
            name='tasks_to_do_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boards',
            name='ticket_count',
            field=models.IntegerField(default=0),
        ),
    ]
