# Generated by Django 5.2.7 on 2025-10-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
