# Generated by Django 5.2.7 on 2025-10-17 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_delete_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='members',
            field=models.ManyToManyField(related_name='members_board', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boards',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
