# Generated by Django 5.2.7 on 2025-10-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_alter_boards_members_alter_boards_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='tasks_to_do_count',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='ticket_count',
        ),
    ]
