# Generated by Django 5.2.7 on 2025-10-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_remove_boards_member_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
